apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32767
  selector:
    app: wordpress
  type: NodePort
status:
  loadBalancer: {}
