apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mysql
  type: ClusterIP
status:
  loadBalancer: {}